version: '3.8'

services:

  db:
    container_name: db
    image: mysql:8
    env_file: .env
    restart: unless-stopped
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    volumes:
      - my-db:/var/lib/mysql

  app:
    depends_on:
      - db
    build: ./Back-end
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  my-db: